### ISSUE TITLE
Logs overflowed by SQLite errors

### ISSUE THREAD

**Issue by VikteBaranauskiene** [iTwin/imodel-transformer#44] opened 2023-05-22 09:48 UTC
This started happening with increased iTwinJs version.

This was happening when creating a transformation state dump and it has subCategory information.
SubCategory information is stored incorrectly within the state dump.

![seq](https://github.com/iTwin/imodel-transformer/assets/99892038/2d4e1928-f54f-45b9-8e6c-97dece9e252d)

**Comment by MichaelBelousov** [comment] 2023-05-22 14:02
do you think we can reproduce with this?

```
class Repro extends IModelTransformer {
  onExportElement(...args) {
    super.onExportElement(...args);
    if (elem instanceof SubCategory)
      this.saveStateToDb();
  }
}
// run that transformer on a source with a subcategory to an empty target 
```

**Comment by ViliusRuskys** [comment] 2023-05-22 14:38
I noticed similar logs when registering SubCategories for filtering like `transformer.context.filterSubCategory(subCategoryId)`.
Then when creating the saved state it spits out a bunch of these error logs.

I also remember checking the saved state with an sqlite explorer, and it seemed that subcategory serialization logic was incorrect.
e.g. If you had 10 different SubCategories registered for filtering, in the saved state generated all 10 ids will be identical pointing to the same Element. Don't know if you were aware of this and if this issue is fixed on the current version though.

**Comment by nick4598** [comment] 2024-10-11 17:01
Closing because saving the state of a currently running transform is no longer supported.

**Closed by nick4598** 2024-10-11 17:01 UTC
